### ISSUE TITLE
`Show placeholder in text input box` toggle doesn't work as of newest build

### ISSUE THREAD

**Issue by brian6932** [Mm2PL/dankerino#117]
**Describe the bug**
No matter the state of the toggle, your name will still appear in the text input box

**To reproduce**
Toggle it

**Screenshots**
![image_79](https://user-images.githubusercontent.com/18603393/142790105-af15a001-665c-4dab-ada2-a878a814b2ee.png)

**Chatterino version**
608965eb

**Operating system**
Windows 10

**Comment by Mm2PL** [comment]
Looks like i fixed not having the placeholder too well lol
