### ISSUE TITLE
Context menu buggy in the textbox 

### ISSUE THREAD

**Issue by lucas19961** [Mm2PL/dankerino#129]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I cannot right klick in the textbox to paste / copy etc

### Screenshots

https://kappa.lol/gO-wY the latest build 

https://kappa.lol/Z3GYt  before

### OS and Chatterino Version

Chatterino Nightly + Dankerino patches 2.3.5 (commit 1c18bf52; based on 76a891c5 modified) built on 2022-08-06 with Qt 5.15.2, Windows SDK, MSVC 193231332 Running on Windows 10 Version 2009, kernel: 10.0.22000

**Comment by Mm2PL** [comment]
This is an upstream issue. Closing in favour of https://[https://github.com/Chatterino/chatterino2/issues/3844]github.com[https://github.com/Chatterino/chatterino2/issues/3844]/Chatterino/chatterino2/issues/3844[https://github.com/Chatterino/chatterino2/issues/3844]. I'll see what I can do but no promises yet.

7 sie 2022 18:46:51 lucas19961 ***@***.***>:

> 
> *Checklist*
> 
* > I'm reporting a problem with Chatterino
* > I've verified that I'm running *the most* recent nightly build or stable release
* > I've looked for my problem on the wiki[https://wiki.chatterino.com/Help/]
* > I've searched the issues and pull requests[https://github.com/Chatterino/chatterino2/issues?q=] for similar looking reports
