### ISSUE TITLE
Chatterino crashed on Twitch reconnect 

### ISSUE THREAD

**Issue by lucas19961** [Mm2PL/dankerino#130]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Whenever chatterino loses the connection to the Twitch servers or Twitch disconnects, chatterino crashes. Chatterino unexpectedly crashed and restarted. You can disable automatic restarts in the settings. Are there any logs where you can look up what could be wrong?

### OS and Chatterino Version

Chatterino Nightly + Dankerino patches 2.3.5 (commit bd9eae2d; based on 756bd90b modified) built on 2022-08-11 with Qt 5.15.2, Windows SDK, MSVC 193231332 Running on Windows 10 Version 2009, kernel: 10.0.22000

**Comment by Felanbird** [comment]
This was fixed by https://github.com/Chatterino/chatterino2/pull/3932
