### ISSUE TITLE
Lowercase autocompleted chatter names 

### ISSUE THREAD

**Issue by Supinic** [Mm2PL/dankerino#18]
**What should be added?**
A way to toggle between having usernames autocompled in *truecase* and *lowercase*. Currently, only *truecase* is supported*.

**Why should it be added?**
IIRC, earlier versions of C2 had usernames be autocompleted as lowercase. The current behaviour is a change without a toggle.

**Comment by Mm2PL** [comment]
https://github.com/Chatterino/chatterino2/pull/1883
