### ISSUE TITLE
Toggle for placeholder message

### ISSUE THREAD

**Issue by Supinic** [Mm2PL/dankerino#19]
**What should be added?**
A way to toggle the placeholder text written in every single chat tab's message prompt.

**Why should it be added?**
It's really annoying to look at. Especially now that it mentions the username of the person logged in. Like, yeah, I get it, it's me who's chatting. I don't need each chat tab to remind me who I am.

**Comment by zneix** [comment]
This issue can be closed since #27 has been merged in.

**Comment by Mm2PL** [comment]
Closed via #27
