### ISSUE TITLE
Chocolatey Package

### ISSUE THREAD

**Issue by brian6932** [Mm2PL/dankerino#39]
A Chocolatey package would be pretty useful to auto update and for moving PCs

**Comment by Mm2PL** [comment]
I've never tried doing this. I'll see what I can do :)

**Comment by alazymeme** [comment]
> especially considering that Chatterino's choco package isn't working atm

I haven't seen any feedback of this. Since I manage the package, it would be cool if I was made aware of it.

**Comment by zneix** [comment]
@brian6932 I just tried Chatterino's choco package last week and it worked perfectly, please define "isn't working". Thanks!

**Comment by brian6932** [comment]
@zneix it was for a short time, it was fixed months ago

**Comment by ALazyMeme** [comment]
Here you go, pending approval from chocolatey: https://community.chocolatey.org/packages/dankerino

**Comment by Mm2PL** [comment]
dankClappers

**Comment by brian6932** [comment]
@ALazyMeme Is this supposed to happen?
![image_249](https://user-images.githubusercontent.com/18603393/130152291-500a3202-b13d-4f1c-b6a9-029268952eab.png)

**Comment by ALazyMeme** [comment]
> @ALazyMeme Is this supposed to happen?
> ![image_249](https://user-images.githubusercontent.com/18603393/130152291-500a3202-b13d-4f1c-b6a9-029268952eab.png)
> 

Not usually, I'll check on what failed when I get home.

**Comment by ALazyMeme** [comment]
It was literally just a url missing. Sometimes I hate this standard.

I've pushed a new build now
