### ISSUE TITLE
IRC Message Logging

### ISSUE THREAD

**Issue by 5E7EN** [Mm2PL/dankerino#63]
**What should be added?**
Support to log messages from (experimental) IRC channels, just like with Twitch channels

**Why should it be added?**
It's cool

**Comment by Mm2PL** [comment]
will look into it

**Comment by Mm2PL** [comment]
Little update: IRC messages don't really have nice `searchText` nor `messageText`, that needs to be added before this.

**Comment by 5E7EN** [comment]
> Little update: IRC messages don't really have nice `searchText` nor `messageText`, that needs to be added before this.

Is this also the reason mentions in IRC channels don't show up in the /mentions tab?

**Comment by Mm2PL** [comment]
That's caused by them being built with another MessageBuilder not the twitch one, which is also the cause of them not having `searchText` nor `messageText`.

**Comment by Mm2PL** [comment]
Moved to upstream a long time ago. Chatterino/chatterino2#2996
