### ISSUE TITLE
Another "Remove spaces between/around emotes" bug

### ISSUE THREAD

**Issue by brian6932** [Mm2PL/dankerino#66]
**Describe the bug**
When "Remove spaces between/around emotes" is enabled, it causes the emote menu to overlap

**Screenshots**
On:
![image](https://user-images.githubusercontent.com/18603393/116374430-44921480-a7dc-11eb-99b8-f12aeab97697.png)
Off:
![image](https://user-images.githubusercontent.com/18603393/116374633-760ae000-a7dc-11eb-8c8f-5751d18c900d.png)

**Chatterino version**
42188345e

**Operating system**
Windows 10

**Comment by Mm2PL** [comment]
note to self: check if it's something to do with 'compact emotes'
