### ISSUE TITLE
As of the past 2 nightly builds @ colors have been broken

### ISSUE THREAD

**Issue by brian6932** [Mm2PL/dankerino#81]
**To reproduce**
Just @ someone in the newest build installed in: `C:\Program Files\Chatterino`

**Screenshots**
Newest nightly:
![image](https://user-images.githubusercontent.com/18603393/120085788-150b4c00-c0a9-11eb-94f4-104a50924efc.png)
f447ed3:
![image](https://user-images.githubusercontent.com/18603393/120085830-60255f00-c0a9-11eb-951b-2d138133ab87.png)

**Chatterino version**
362aadc62

**Operating system**
Windows 10

**Comment by brian6932** [comment]
Or at least it seems to occur when in install directory, but not when ran in it's own portable directory

**Comment by brian6932** [comment]
It seems to also occur without moving directories too, although it's a little more inconsistent

**Comment by Mm2PL** [comment]
This is a known upstream bug. Duplicates Chatterino/Chatterino2#2822

**Comment by brian6932** [comment]
@Mm2PL oh I see
